apiVersion: v1
kind: Service
metadata:
  name: quarkus-java-front-service
spec:
  type: LoadBalancer
  selector:
    app: quarkus-java-front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-java-back-service
spec:
  type: LoadBalancer
  selector:
    app: quarkus-java-back
  ports:
  - name: p1
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: p2
    protocol: TCP
    port: 8080
    targetPort: 8080
